/**:
  ros__parameters:
    wheel_radius: 0.303.9 # The radius of the wheel, primarily used for dead reckoning.
    wheel_width: 0.215 # The lateral width of a wheel tire, primarily used for dead reckoning.
    wheel_base: 1.6 # between front wheel center and rear wheel center
    wheel_tread: 1.2 # between left wheel center and right wheel center
    front_overhang: 0.393 # between front wheel center and vehicle front
    rear_overhang: 0.393 # between rear wheel center and vehicle rear
    left_overhang: 0.083 # between left wheel center and vehicle left
    right_overhang: 0.083 # between right wheel center and vehicle right
    vehicle_height: 2.5
    max_steer_angle: 0.70 # [rad]
